#!/usr/bin/env python3
# Writes native/psp_launcher/charset_th10_unicode.inc for the launcher's text
# table maker (text_table.cpp): charset_th10.bin split into its Shift_JIS codes
# in file order and decoded with Python's cp932 codec, as make_font_msgothic.py
# reads it. Codes the codec refuses are kept as 0xFFFFFFFF and skipped there
# too, so both tools see the same list.
#
# usage: gen_charset_unicode.py [charset_th10.bin] [output .inc]
#        gen_charset_unicode.py --check   (exit 1 when the .inc is stale)
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CHARSET = os.path.join(HERE, 'charset_th10.bin')
DEFAULT_OUTPUT = os.path.join(HERE, '..', '..', 'native', 'psp_launcher', 'charset_th10_unicode.inc')

def render(charset):
    cs = open(charset, 'rb').read(); rows = []; i = 0
    while i < len(cs):
        c = cs[i]
        b = cs[i:i + 2] if (0x81 <= c <= 0x9f or 0xe0 <= c <= 0xfc) else cs[i:i + 1]
        i += len(b)
        code = b[0] if len(b) == 1 else (b[0] << 8) | b[1]
        try:
            ch = b.decode('cp932')
            assert len(ch) == 1
            unicode = ord(ch)
        except UnicodeDecodeError:
            unicode = 0xFFFFFFFF
        rows.append((code, unicode))
    lines = ['// Generated by tools/fonts/gen_charset_unicode.py from charset_th10.bin',
             f'// ({len(cs)} bytes, {len(rows)} codes); do not edit.',
             '// {Shift_JIS code, Unicode from cp932 or 0xFFFFFFFF when undecodable}']
    for n in range(0, len(rows), 6):
        lines.append(' '.join(f'{{0x{c:04X},0x{u:X}}},' for c, u in rows[n:n + 6]))
    return '\n'.join(lines) + '\n'

def main():
    args = sys.argv[1:]
    check = '--check' in args
    args = [a for a in args if a != '--check']
    charset = args[0] if args else DEFAULT_CHARSET
    output = args[1] if len(args) > 1 else DEFAULT_OUTPUT
    text = render(charset)
    if check:
        current = open(output, encoding='ascii').read() if os.path.exists(output) else ''
        if current != text:
            sys.exit(f'{output} is stale; run {os.path.basename(__file__)}')
        print('charset table up to date')
        return
    open(output, 'w', encoding='ascii', newline='\n').write(text)
    print('wrote', output)

if __name__ == '__main__':
    main()
